version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_server
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'P@ssw0rd'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    restart: unless-stopped
